version: '3.8'

services:
  react-frontend:
    container_name: frontdbcourse
    build:
      context: ./front
      target: production
    ports:
      - 3000:3000
      - 8000:80
    depends_on:
      - db
      - app

  app:
    build:
      context: ./coke
    container_name: appdbcourse
    ports:
      - 5000:5000
    depends_on:
      - db
    restart: unless-stopped

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: postgresdbcourse
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-migregal}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1234}
      PGDATA: /data/postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data/
      - ./dataset:/dataset
      - ./queries:/queries
    ports:
      - 5432:5432
    restart: unless-stopped
